version: 0.2
run-as: root

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.......
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 789934552839.dkr.ecr.ap-south-1.amazonaws.com
      - # Replace with this to your repository URI
      - REPOSITORY_URL=789934552839.dkr.ecr.ap-south-1.amazonaws.com/ecs-ecr-testing
      - IMAGE_TAG=refTag
  build:
    commands:
      - echo Build started on `date`
      - echo Docker image is building... 
      - npm --version
      - npm install express
      - npm install prom-client
      - docker build -t containertesting .
      - docker tag containertesting refTag   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to AWS ECR .....
      - docker push containertesting 
      - echo ECS Configuration....
      - echo Writing image definitions file...
      - CONTAINER_NAME=ecr-ecs-testing
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME containertesting > imagedefinitions.json
      - cat imagedefinitions.json   
artifacts:
    files: imagedefinitions.json
