version: 0.2
run-as: root

secrets-manager:
    SECRET_VALUE: "arn:aws:secretsmanager:ap-south-1:789934552839:secret:keeper-container-ecr-creds-LJ64pX"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.......
      - $ECR_LOGIN_STRING
      - # Replace with this to your repository URIs
      - REPOSITORY_URL=$ECR_REPO_URI
      - IMAGE_TAG=reftag
  build:
    commands:
      - echo Build started on `date`
      - echo Docker image is building... 
      - npm --version
      - npm install express
      - npm install prom-client
      - docker build -t $REPOSITORY_URL .
      # - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to AWS ECR .....
      - docker push $REPOSITORY_URL
      - echo ECS Configuration....
      - echo Writing image definitions file...
      - CONTAINER_NAME=ecr-ecs-testing
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME containertesting > imagedefinitions.json
      - cat imagedefinitions.json   
artifacts:
    files: imagedefinitions.json
